services:
    directus:
        container_name: ${STACK_PRFX}-directus
        image: directus/directus:11.5.1
        ports:
            - 8055:8055
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        env_file:
            - .env
        # depends_on:
            # database:
            #     condition: service_healthy
            # cache:
            #     condition: service_started
        networks:
            - directus-network


    # TO connect with existing rollinbackend db so it will not run
    # database:
    #     container_name: ${STACK_PRFX}-database
    #     platform: linux/x86_64
    #     image: mysql:8.4
    #     ports:
    #         - 3307:3306 # Changed from 3307:3307
    #     volumes:
    #         - ./database:/var/lib/mysql:rw
    #     command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--mysql-native-password=ON"]
    #     env_file:
    #         - .env
    #     networks:
    #         - directus-network
    #     healthcheck:
    #         test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #         start_period: 30s


    # Cache
    # cache:
    #     container_name: ${STACK_PRFX}-cache
    #     image: redis:7.0-alpine
    #     networks:
    #         - directus-network
    #     healthcheck:
    #         test: ["CMD", "redis-cli", "ping"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #         start_period: 10s

networks:
  directus-network:
    name: ${STACK_PRFX}
    driver: bridge